# Generated by Django 4.0.4 on 2022-09-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='credit_card',
            field=models.IntegerField(default=9599018445787602, null=True),
        ),
    ]
