# Generated by Django 4.0.4 on 2022-09-13 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='credit_card',
        ),
    ]
