# Generated by Django 4.0.4 on 2022-09-12 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={},
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transactions',
            name='receiver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_transactions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
