# Generated by Django 4.0.4 on 2022-09-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_alter_bankaccount_options_alter_transactions_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='account_type',
            new_name='receiver_account_type',
        ),
    ]
