# Generated by Django 4.0.4 on 2022-09-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_rename_account_type_transactions_receiver_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='receiver_account_type',
        ),
    ]
