# Generated by Django 4.0.4 on 2022-09-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_remove_transactions_receiver_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='ts_type',
            field=models.CharField(choices=[(1, 'send'), (2, 'deposit'), (3, 'withdraw')], default=2, max_length=20, null=True),
        ),
    ]
