# Generated by Django 4.0.4 on 2022-09-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_transactions_ts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='ts_type',
            field=models.CharField(choices=[(1, 'send'), (2, 'deposit'), (3, 'withdraw'), (4, 'Credit Card')], default=2, max_length=20, null=True),
        ),
    ]
