# Generated by Django 4.1.1 on 2022-09-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_transactions_ts_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
